#https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#https://github.com/marketplace/actions/setup-node-js-environment
#https://github.com/marketplace/actions/sftp-deploy  alternative
#https://github.com/marketplace/actions/ssh-deploy
#Edit on GitHub online with prompt.


name: Deployed Vue.js Project to Cloud Server via SSH
on:
  push:
    branches:
      [ main, master]
  label:
    types: [ created ]


jobs:
  job1:
    name: job1. Build dist
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Print node version
        run: |
          node -v
          npm -v
      - name: Install dependencies, Build, Test
        run: |
          npm install --loglevel verbose
          npm run build
      - name: Check dist dir
        run: ls -al dist/
      - name: Deploy static dist files to server via sftp
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: root
          server: 49.4.82.110
          port: 22
          local_path: ./dist/*
          remote_path: /Apps/my_portfolio/dist/

